name: Build Zed Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build release
        env:
          RUSTFLAGS: -C target-cpu=alderlake
        run: |
          cargo build --release

      - name: Archive build
        run: |
          Compress-Archive -CompressionLevel Optimal -Path target/release/zed.exe -DestinationPath zed-windows.zip

      - name: Get the current date
        run: |
          $CURRENT_DATE = Get-Date -Format "yyyy-MM-dd"
          echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_ENV

      - name: Upload release build artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: zed-windows.zip
